apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leantime-manual
  namespace: leantime
spec:
  ingressClassName: traefik
  rules:
    - host: tasks.kbrt.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: leantime-helm
                port:
                  number: 80
