apiVersion: v1
kind: ConfigMap
metadata:
  name: element-web-config
  namespace: matrix
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "https://matrix.kbrt.xyz",
                "server_name": "matrix.kbrt.xyz"
            },
            "m.identity_server": {
                "base_url": "https://vector.im"
            }
        },
        "brand": "KBRT Chat",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "integrations_widgets_urls": [
            "https://scalar.vector.im/_matrix/integrations/v1",
            "https://scalar.vector.im/api",
            "https://scalar-staging.vector.im/_matrix/integrations/v1",
            "https://scalar-staging.vector.im/api",
            "https://scalar-staging.riot.im/_matrix/integrations/v1",
            "https://scalar-staging.riot.im/api"
        ],
        "show_labs_settings": true,
        "features": {
            "feature_sliding_sync": true
        },
        "default_theme": "dark"
    }
